# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Physical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usr',
            name='passwd',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='usr',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
